package com.exceptions;

import java.util.Scanner;

public class FinallyException {

	public static void main(String[] args) {
		Scanner sc=null;
		try {
			sc=new Scanner(System.in);
			int a=sc.nextInt();
			
		} catch (Exception e) {
			// TODO: handle exception
		}finally {
			sc.close();
		}

	}

}
