package com.exceptions;

import java.util.Scanner;

public class Practice1 {
    
    
    static void validateNumber(int num) throws IllegalArgumentException, ArithmeticException {
        if (num < 0) {
            throw new IllegalArgumentException("Negative number not allowed!");
        } else if (num == 0) {
            throw new ArithmeticException("Zero is not a valid input!");
        } else {
            System.out.println("Valid number entered: " + num);
        }
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        
        try {
            System.out.print("Enter a number: ");
            int num = sc.nextInt();  
            validateNumber(num);    
        } 
        catch (IllegalArgumentException e) {
            System.out.println("Exception: " + e.getMessage());
        } 
        catch (ArithmeticException e) {
            System.out.println("Exception: " + e.getMessage());
        } 
        
    }
}
